# Make file


all: c2enc_add c2enc_strip

c2enc_add:  Makefile c2encap.h c2enc_add.c
	gcc -O3 -Wall -o c2enc_add c2enc_add.c

c2enc_strip:  Makefile c2encap.h c2enc_strip.c
	gcc -O3 -Wall -o c2enc_strip c2enc_strip.c
