gmsksender: gmsksender.c buffer.h dspstuff.h dstarheader.h dvtool.h fcs.h global.h gmskmodulate.h parsecliopts.h readdvtool.h rewriteheader.h writefile.h input.h alsaout.h
	 gcc -Wall -lpthread -lrt -lasound -o gmsksender gmsksender.c
